<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>ScimStudio</AssemblyName>
    <RootNamespace>ScimStudio.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/scimstudio.ico</ApplicationIcon>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
    <EmbeddedResource Include="Localization/*.json" LogicalName="ScimStudio.App.Localization.%(Filename)%(Extension)" WithCulture="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ScimStudio.Core/ScimStudio.Core.csproj" />
    <ProjectReference Include="../ScimStudio.DemoServer/ScimStudio.DemoServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ScimStudio.App.Tests" />
  </ItemGroup>

</Project>
